server:
  devtools:
    restart:
      enabled: false
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        diarect: org.hibernate.dialect.PostgreSQL10Dialect # 쿼리의 기준이 되는 데이터베이스 엔진을 설정합니다.
        show_sql: true  # sql 쿼리를 보여줍니다.
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql 쿼리의 추가정보를 보여줍니다.
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres2
    username: steady
    password: awds4646592
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      pool-name: HikariPool-1
      keepalive-time: 30000 # 30초마다 keep-alive 실행
      validation-timeout: 5000 # 5초 내에 커넥션 검증
  kafka:
    producer:
      bootstrap-servers: localhost:9092 # Kafka cluster 초기 연결 Port
  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: when_missing
        embedding:
          additional-models:
            - mxbai-embed-large
            - nomic-embed-text
        timeout: 60s
        max-retries: 1
      chat:
        options:
          model: llama3.2
          temperature: 0.5
          top-p: 0.5
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1024
        batching-strategy: TOKEN_COUNT # Optional: Controls how documents are batched for embedding
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
