global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Spring Boot Actuator 메트릭 수집
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      # Mac/Windows Docker Desktop
      - targets: ['host.docker.internal:8080']
        # Linux의 경우 아래 주석 해제하고 위 라인 주석 처리
        # - targets: ['172.17.0.1:8080']
        labels:
          application: 'demo-app'
          environment: 'local'

  # Prometheus 자체 메트릭
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
