# API 버전 (Grafana provisioning API 버전)
apiVersion: 1

# 삭제할 데이터소스 목록 (기존 데이터소스 정리)
deleteDatasources:
  # 이름이 'Prometheus'인 데이터소스를 삭제
  - name: Prometheus
    # 조직 ID (기본값 1)
    orgId: 1

# 프로비저닝할 데이터소스 목록
datasources:
  # 데이터소스 이름 (Grafana UI에서 보이는 이름)
  - name: Prometheus
    # 데이터소스 타입 (prometheus, mysql, elasticsearch 등)
    type: prometheus
    # 접근 방식: proxy = Grafana 서버를 통해 접근
    # direct = 브라우저에서 직접 접근
    access: proxy
    # Prometheus 서버의 URL
    # Docker 네트워크 내에서는 서비스 이름으로 접근 가능
    url: http://prometheus:9090
    # 기본 데이터소스로 설정 (대시보드에서 자동 선택)
    isDefault: true
    # JSON 형식의 추가 설정
    jsonData:
      # 쿼리 타임아웃 (초)
      httpMethod: POST
      # Exemplar 기능 활성화 (트레이싱 연동용)
      exemplarTraceIdDestinations: []
    # 설정 버전 (업데이트 시 증가시켜야 함)
    version: 1
    # 편집 가능 여부 (false = UI에서 수정 불가)
    editable: false
